### ISSUE TITLE
How to know if image has been edited or untouched?

### ISSUE THREAD

**Issue by DukeManh** [scaleflex/filerobot-image-editor#127]
Hello,
Thanks for this wonderful project

My app uses Filerobot editor and I want to know if an image has been edited or not, so I can replace the original image otherwise there is no need to do update it.

**Comment by AhmeeedMostafa** [comment]
Hello @DukeManh , thanks for your comment.,

Since we are only returning the modified image with its meta (name, mime) only it might be hard to know if the image is edited or not,
but in our new major version that's almost coming this month, such a feature would be considered as well as you would be able to receive the edits separately.

**Comment by DukeManh** [comment]
@AhmeeedMostafa, thanks for your response.
I really look forward to the next major release.

In the meantime, I have a workaround that would check if the `Undo` button is disabled to tell the image has been edited or not. It's not the ideal one because it relies on CSS.

I think in the next release, it'll be cool to have a `onApply`  handle prop, so we have more control over what has been done on the image.

**Comment by AhmeeedMostafa** [comment]
Hey @DukeManh new [V4](https://github.com/scaleflex/filerobot-image-editor/tree/v4) is released in BETA now it would be nice if you want to check your issue and let us know the feedback
We have considered adding possibility to customize tabs, and also having the design state for the image onSave please give it a look and let us know your feedback
