### ISSUE TITLE
lockScaleToPercentage not working

### ISSUE THREAD

**Issue by cggit** [scaleflex/filerobot-image-editor#129]
My understand is that lockScaleToPercentage should scale down the watermark image.
I haven't been able to make it work. Version 3.12.17

`watermark: {
                            position: 'right-bottom',
                            opacity: 1,
                            lockScaleToPercentage:10,
                            url: 'https://example.png'
                       }`

Am I missing something?

Thank you

**Comment by AhmeeedMostafa** [comment]
hey @cggit , for watermark we already had a new feature to scale the image 33% , seems this feature overrides the locakScaleToPercentage

but as we are working on the new version currently we don't have the time to maintain the old version as the new one would have more features so I'd recommend to wait for the new version

**Comment by AhmeeedMostafa** [comment]
@cggit since we have expanded the options/properties for watermark through the user side in the new version, such a property is not supported anymore please consider checking the new docs for the new version [V4](https://github.com/scaleflex/filerobot-image-editor/tree/v4) is released in BETA now it would be nice if you want to check your issue and let us know the feedback
