### ISSUE TITLE
Multiple Watermarks

### ISSUE THREAD

**Issue by oliverzwack** [scaleflex/filerobot-image-editor#143]
Hi,
we use your tool to place stickers on faces. For this we use the Watermark function. Is it possible to set multiple watermarks? Currently, unfortunately, only one watermark can be edited at a time. Is there any workaround?
Thanks for your help!!

**Comment by AhmeeedMostafa** [comment]
Hey @oliverzwack , in fact it is not expected for "watermark" use-case to have multiple watermarks so that we are limiting it for just 1 watermark otherwise you could use the image tool in annotate tab it would give you the possibility to add multiple images as free as you want...
if you are talking about preloaded images or provided images to the user we would support that in the upcoming features

**Comment by rferreira98** [comment]
@AhmeeedMostafa is it possible to annotate images automatically without the ui provided?

**Comment by AhmeeedMostafa** [comment]
> @AhmeeedMostafa is it possible to annotate images manually/programatically without the ui provided?

It might be possible through `loadableDesignState` property check it in the docs.

**Comment by rferreira98** [comment]
@AhmeeedMostafa did so, although had a weird issue. Using useState to get the source image width and height, and only loading editor when both of these are ready, breaks the loadingState.
If i give static values all works well, but if not...
Would have some insights regarding this issue?
