### ISSUE TITLE
Ubuntu + Chromium or Chrome : Crop corner cannot be dragged

### ISSUE THREAD

**Issue by K20** [scaleflex/filerobot-image-editor#161]
Hello, 

With : 
- Ubuntu 20.04.4 LTS
- Version 99.0.4844.51 (64 bits) Chrome or Chromium

The crop cannot be resized. We tested with another linux (Fedora 35) and it works. It also works on Firefox.

You can see an example in this video : https://we.tl/t-io4Y2J7H2L

There's no Javascript error in console.

**Comment by AhmeeedMostafa** [comment]
v3 has different problems that are fixed in v4, but fixing them in v3 will take time for nothing as very soon v4 will become in prod. as it became more mature now, so better to check out v4 and if u still have the same issue please report it or wait till it become in prod. and start using it (if you have the solution for v3 your PR is welcomed as we have no time to keep supporting v3 and improve v4)
