### ISSUE TITLE
Button Type

### ISSUE THREAD

**Issue by CronosUnder** [scaleflex/filerobot-image-editor#268]
the button type can be added to the buttons, since when pressing them and being inside a form, they launch the submit event,

context:
react, formik

**Comment by jgab-net** [comment]
the solution for the button is to update the design-system library dependency, I don't know if version 2 is compatible, but between 1.0.0-beta.80 and 1.0.0-beta.99 is the change.

https://github.com/scaleflex/ui/blob/1.0.0-beta.80/packages/ui/src/core/button/button.component.tsx
https://github.com/scaleflex/ui/blob/1.0.0-beta.99/packages/ui/src/core/button/button.component.tsx

we need to change it in the package.json

https://github.com/scaleflex/filerobot-image-editor/blob/master/packages/react-filerobot-image-editor/package.json#L33

we were able to temporarily resolve the issue with:

  ```
"resolutions": {
    "**/@scaleflex/ui": "1.0.0-beta.90"
  }
```
because we use yarn workspace...

BUT, these will still cause problems in other buttons, because the icon-button component of the design-system does not have the type el added in any version. 🤦🏻
