### ISSUE TITLE
Finetune : blur effect bug 

### ISSUE THREAD

**Issue by smokeninja77** [scaleflex/filerobot-image-editor#273]
There is a bug I noticed happen on filerobot demo, the sensitivity of the blur effect is different from the image downloaded.

**Comment by AhmeeedMostafa** [comment]
Quickly checked and seems u are right, labeled as bug till we have time to deeply check it and have a solution,
thanks for reporting @smokeninja77

**Comment by AhmeeedMostafa** [comment]
@smokeninja77 actually after deeply checking, it is not a bug it is just because in the demo we are decreasing the preview resolution/quality through the prop `previewPixelRatio` for better performance while doing the operations so the resolution is not that clear, and on saving we use the original/improved resolution for the image so the resolution is more clear after saving so that u notice the blur changes a bit as on applying blur for low resolution the blur is shown more & more than the higher resolution one.
