### ISSUE TITLE
Pressing 'Enter' + clicking outside the textarea should save the text

### ISSUE THREAD

**Issue by Ender22** [scaleflex/filerobot-image-editor#275]
We've focus-tested this image editor with 10 users, with the basic task of putting some text over an image. All 10 of them failed the task. It seems completely unintuitive for a normal user that they would need to press 'enter' in order to save the results of the text they are typing. 

All of them instead clicked outside of the text box when they finished typing and then were super surprised that the text reverted to the default text before typing anything.

I'm really surprised this isn't a major complaint about the tool. Is there any way that we can change this strange behavior? 

Thanks for any help or tips

**Comment by AhmeeedMostafa** [comment]
@Ender22 well I'm really surprised from the issue's title ... this behavior is already going to be considered in the upcoming versions but it is not a blocker for the user to have the tool 'unusable' !

**Comment by Ender22** [comment]
If the experience of a product frustrates users and they can't do what they want with it, it is the same as being unusable... maybe you don't have much experience with the UX side of things...

**Comment by AhmeeedMostafa** [comment]
I don't know u to expect smth from u!, if it is unusable at all u could dismiss using it then otherwise suggest in a clear way what is needed. It's my mistake from the beginning to answer and ask u to consider clear issue's title with proper words than mentioning unusable in general.
Finally, we already have an issue #239 that requested such behavior before, closing the issue as it's duplicated.
