### ISSUE TITLE
Toolbar Bug when you "Apply" 

### ISSUE THREAD

**Issue by thanhhoa214** [scaleflex/filerobot-image-editor#36]
# Toolbar Bug when you "Apply" 
- **Target**: Effects or all Toolbar items. 
- **Description**: Effects apply on image but Toolbar state did not update. So the next time if you want to reset only that effect seemly impossible.
- **Attached**: I reproduce it in ZIP file.

[EffectBug.zip](https://github.com/scaleflex/filerobot-image-editor/files/4207687/EffectBug.zip)

@dzmitry-stramavus Check it & hope your team fix it soon.
It's great to hear some good news whenever releases new upgrade!

**Comment by dzmitry-stramavus** [comment]
hey @thanhhoa214,

thx for reporting. However, it's expected behavior. After clicking apply filters, you merge layers into one. This is done in order to save processing time. You can still "reset" your adjustments with go back button (left bottom corner):

![image](https://user-images.githubusercontent.com/10708539/74682448-bf21d600-51ce-11ea-8899-9d1e92ed8d68.png)

As for now, we put speed over layers. Tell me if you have strong reason to change this behavior. Anyway, thx for contributing.
