### ISSUE TITLE
 Image Editor Custom

### ISSUE THREAD

**Issue by tnstjd120** [scaleflex/filerobot-image-editor#441]
It would be nice to be able to adjust the positions of tools or tabs.

Furthermore, I would like to be able to use the actions of each tool's functions using the buttons I created.

I think this will allow for greater freedom of customization.

**Comment by AhmeeedMostafa** [comment]
I'm quite confused about your request, maybe you could clarify more?

Do you mean exposing an API for the functionalities and using them from your UI?

Anyway, we have good plans towards the editor to make it more customizable but not enough time to apply that yet and this might be considered in these plans but no specific timeline due to lack of time availability.

**Comment by tnstjd120** [comment]
I would like to provide an API for the function and use it by applying it to the user-created UI.

It's a pity that there is no specific schedule yet.

**Comment by tnstjd120** [comment]
I would like to provide an API for the function and use it by applying it to the user-created UI.

It's a pity that there is no specific schedule yet.
