### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by gautiermichelin** [scaleflex/filerobot-image-editor#470]
Hi @AhmeeedMostafa 
I've found a bug implying the stroke width. Default value through :

```
var config = {
  source: "https://scaleflex.cloudimg.io/v7/demo/river.png",
  annotationsCommon: { strokeWidth: 5}
};
```
But with what's next, it is :
```
var config = {
  source: "https://scaleflex.cloudimg.io/v7/demo/river.png",
  Pen: {
    strokeWidth: 5,
  }
};
```

I'd like to correct such small things and be able to make some PR for some documentations, but I'm not able to compile on my mac. 

<img width="1451" alt="image" src="https://github.com/scaleflex/filerobot-image-editor/assets/314697/8e9f6540-d20a-41ca-b070-5df1190db8bf">

Could you make a simple developer doc on how to compile ?
There seem to be some incompatibility in the libs with rollup for example, and you may have some custom tricks to build :-)

Best regards,

Gautier

**Comment by AhmeeedMostafa** [comment]
@gautiermichelin if you want to check something in dev mod then you should use `yarn dev` command, that's all
if you want to build a JS bundle, you would use the command you are using in the screenshot, but the error you are facing  is because you didn't transpile the source code (and currently our build options, for bundling depends on the transpiled lib. version)
so you should first run `yarn build:packages` then `yarn build:js-bundle`
