### ISSUE TITLE
Receiving an error at the start

### ISSUE THREAD

**Issue by SmitKakani7** [scaleflex/filerobot-image-editor#476]
When trying to integrate  filerobot-image-editor into a new React app, an error occurs during start.

![image](https://github.com/scaleflex/filerobot-image-editor/assets/132330039/9ce7814a-90e7-4e7e-aeb8-bd9fa31b9f46)

[package.json](https://github.com/user-attachments/files/15934979/package.json)

**Comment by jonasao** [comment]
@SmitKakani7 seems like the FileRobotImageEditor component is executing two requests against
```https://i18n.ultrafast.io/api/export?grid=353297d2-40b4-4684-a875-45a2178a8157```
...which fails and results in the exceptions you're experiencing. 

I am experiencing the same, and it probably has something to do with translation of the component's text-strings, so the question will be: Is it possible to disable translation and thereby preventing these requests?

**Comment by jonasao** [comment]
@SmitKakani7 
Have you tried adding: 
`<FileRobotImageEditor useBackendTranslations={false} ........>`

This solved this issue for me.

**Comment by AhmeeedMostafa** [comment]
@SmitKakani7 that issue happens due to the backend translations endpoint as @jonasao mentioned.

we changed the endpoint and would be considered in the next release, temporarily you could disable the backend translations from the same property provided by @jonasao and you could provide your own translations if wanted.
