### ISSUE TITLE
Mobile issues: Text, Image

### ISSUE THREAD

**Issue by elmarrr** [scaleflex/filerobot-image-editor#73]
Hey,
when I add something like text, I can't drag it on mobile.
Not on my phone, not in dev tools. On desktop all works fine.
In any Browser on this url for example https://scaleflex.github.io/filerobot-image-editor/
Tried to update Chrome and Firefox.
In Firefox the dragpoints fall together to one point.

Could you please check it? I would like to use your tool soon.

Thank you very much!

**Comment by AhmeeedMostafa** [comment]
Hello @elmarrr ,
Sorry for the late response, we have already added support for touch for moving objects' places only in the new release v3.11.2,
we would consider adding touch support for other operations too in the feature.
Thanks!

**Comment by elmarrr** [comment]
Hey,
thank you for the response.
I noticed 2 issues with the drag with v3.11.3

When I firstly add a text it is already selected, but I can't drag it. I have to tap on it before and then I can drag it. And when I cancel it and after cancel add text again and drag it, then the text disappears.

Should I open a new Issue or is it enough so it does not get lost.

Thank you!

**Comment by AhmeeedMostafa** [comment]
Hey @elmarrr ,
Since touch d&d support isn't 100% finalized yet maybe some issues like that would shown up, we are going to consider that when implementing the full support for touch.

You don't need to have a new issue since we are considering this issue
Thank you for your report and if you faced any such strange behavior let us know.

**Comment by elmarrr** [comment]
Thank you!
