### ISSUE TITLE
Unmount fails with Javascript Version

### ISSUE THREAD

**Issue by nguernse** [scaleflex/filerobot-image-editor#80]
Thanks for this cool package!

If I try to unmount the image editor it throws the error:
```
filerobot-image-editor.min.js:88 Uncaught ReferenceError: container is not defined
    at e.value (filerobot-image-editor.min.js:88)
    at e.unmount (filerobot-image-editor.min.js:88)
    at HTMLButtonElement.<anonymous> (?editor_console=true:120)
```

Here's a jsfiddle example of the bug: [https://jsfiddle.net/9r7gvk30/](https://jsfiddle.net/9r7gvk30/)

Is there something additional I need to add to the code for this to work? Was wanting to unmount the editor at the end of a component lifecycle to prevent memory leaks. Thanks!

--

Sorry if this goes beyond scope of this issue, but is there a way to change the default text of the "Download" button to say something like "Save"? Could not find that in the documentation or where to place it in the config object.

UPDATE: I figured out the default text. Just have to add it in the translations config as:
```
config {
    translations: {
        en: { 'toolbar.download': 'My Text Here' }
    }
}
```

**Comment by AhmeeedMostafa** [comment]
Hello @nguernse ,
sorry for the late response but this is not a bug it's pretty expected behaviour when you don't have the element in your page
per your example you won't be able to click over unmount button unless you close the editor and if you already closed the editor it has unmounted which removes the container which means the container is undefined for the page now!
hope I was clear!
